import React from "react";
import { ReactNavbar } from "overlay-navbar";
import logo from "../../../images/logo.png";

const options = {
  
  logoWidth: "20vmax",
  navColor1: "white",
  logoHoverSize: "10px",
  logoHoverColor: "#eb4034",
  link1Text: "Home",
  link2Text: "Products",
  link3Text: "Contact",
  link4Text: "About",
  link1Url: "/",
  link2Url: "/products",
  link3Url: "/contact",
  link4Url: "/about",
  link1Size: "1.3vmax",
  link1Color: "rgba(35, 35, 35,0.8)",
  nav1justifyContent: "flex-end",
  nav2justifyContent: "flex-end",
  nav3justifyContent: "flex-start",
  nav4justifyContent: "flex-start",
  link1ColorHover: "#eb4034",
  link1Margin: "1vmax",
  profileIconUrl: "/login",
  profileIconColor: "rgba(35, 35, 35,0.8)",
  searchIconColor: "rgba(35, 35, 35,0.8)",
  cartIconColor: "rgba(35, 35, 35,0.8)",
  profileIconColorHover: "#eb4034",
  searchIconColorHover: "#eb4034",
  cartIconColorHover: "#eb4034",
  cartIconMargin: "1vmax",
  burgerColor: 	"black" ,
burgerColorHover: 	"burgerColor"	,
navColor1 :	"rgb(35, 35, 35)" ,	
navColor2: 	"navColor1", 	
navColor3 :	"navColor2" ,	
navColor4 :	"navColor3" ,	
logo ,	
logoWidth:	"100px",	
logoHeight :	"unset" ,	
logoHoverSize :	"15px" ,	
logoHoverColor :	"green", 	
logoTransition :	"0.5" ,	
logoAnimationTime :	"1" ,	
nav1FlexDirection :	"row" ,
nav2FlexDirection :	"row" ,	
nav3FlexDirection :	"row" ,	
nav4FlexDirection :	"row" ,	
nav1alignItems :	"center", 
nav2alignItems :	"center" ,	
nav3alignItems :	"center" ,	
nav4alignItems :	"center" ,	
nav1justifyContent: 	"center" ,	
nav2justifyContent :	"center" ,	
nav3justifyContent :	"center", 	
nav4justifyContent :	"center", 	
nav1Transition: "0.4" ,	
nav2Transition: 	"nav1Transition + 0.4" ,	
nav3Transition :	"nav2Transition + 0.4" ,	
nav4Transition :	"nav3Transition + 0.4" ,
link1Text :	"Text 1" ,	
link2Text :	"Text 2", 	
link3Text :	"Text 3", 	
link4Text :	"Text 4" ,	
link1Url :	"/text1", 
link2Url :	"/text2" ,
link3Url :	"/text3" ,	
link4Url :	"/text4", 	
link1Size :	"1vmax" ,	
link2Size :	"link1Size" ,	
link3Size:	"link2Size" ,	
link4Size :	"link3Size", 
link1Family:	"Roboto", 
link2Family: 	"link1Family", 	
link3Family :	"link2Family" ,	
link4Family :	"link3Family" ,	
link1Color: 	"black" ,
link2Color: 	"link1Color ", 	
link3Color :	"link2Color " ,	
link4Color :	"link3Color " ,	
link1BackgroundColor :	"unset" ,	
link2BackgroundColor :	"unset" ,	
link3BackgroundColor :	"unset" ,	
link4BackgroundColor :	"unset" ,	
link1ColorHover :	"link1Color", 	
link2ColorHover :	"link1ColorHover", 	
link3ColorHover :	"link2ColorHover " ,	
link4ColorHover: 	"link3ColorHover " ,	
link1Decoration :	"none" ,	
link2Decoration :	"link1Decoration" ,	
link3Decoration :	"link2Decoration", 	
link4Decoration :	"link3Decoration" ,	
link1Margin :	"0" ,	
link2Margin :	"link1Margin " ,	
link3Margin :	"link2Margin " ,	
link4Margin :	"link3Margin " ,	
link1Padding :	"0" ,	
link2Padding: 	"link1Padding", 
link3Padding :	"link2Padding" ,
link4Padding :	"link3Padding " ,	
link1Border :	"none" ,	
link2Border :	"link1Border" ,	
link3Border :	"link2Border" ,	
link4Border :	"link3Border" ,	
link1Transition: 	"0.5" ,	
link2Transition: 	"link1Transition" ,	
link3Transition :	"link2Transition" ,	
link4Transition :	"link3Transition" ,	
link1AnimationTime :	"1.5" ,	
link2AnimationTime :	"link1AnimationTime",
link3AnimationTime :	"link2AnimationTime", 	
link4AnimationTime :	"link3AnimationTime", 	
searchIcon :	"true", 	
cartIcon :	"true", 	
profileIcon :	"true" ,	
searchIconMargin :	"0" ,
cartIconMargin 	:"0", 	
profileIconMargin :	"0", 	
searchIconUrl :	"/search" ,	
cartIconUrl :	"/cart" ,	
profileIconUrl :	"/account" ,
searchIconSize :	"2vmax", 	
cartIconSize :	"2vmax" ,	
profileIconSize:"2.5vmax" ,
searchIconColor :	"white", 
cartIconSize :"white", 	
profileIconColor: 	"white" ,	
searchIconColorHover: 	"searchIconColor", 	
cartIconColorHover: 	"cartIconColor", 	
profileIconColorHover: 	"profileIconColor", 	
searchIconTransition :	"0.5" ,	
cartIconTransition :	"0.5" ,	
profileIconTransition :	"0.5" ,	
searchIconAnimationTime :	"2" ,	
cartIconAnimationTime :	"searchIconAnimationTime + 0.5" ,
profileIconAnimationTime :	"cartIconAnimationTime + 0.5" ,	
};

const Header = () => {
  return <ReactNavbar {...options} />;
};

export default Header;
